[package]
name = "entities"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "entities"
path = "./src/lib.rs"

[dependencies]
serde="1.0.200"
serde_json = "1.0.116"

[dependencies.sea-orm]
version = "~1.1.12" # sea-orm version
